const assert = require('assert');
const { createSandbox, load } = require('./helpers/browser-sandbox');
const sb=createSandbox();
load('assets/js/core/00-runtime.js',sb);
load('assets/js/modules/forecast-scenarios.js',sb);
const fs=sb.window.VG.forecast;
const base={available:true,forecastOcc:50,availableRN:1000,adrBase:100,nonRoomPerRN:20,personnelRatio:.20,otherCostRatio:.50,sedeRatio:-.02};
base.baseRevenue=fs.revenueProjection(base,{occDelta:0,adrPct:0,otherRevenuePct:0}).revenue;
const b=fs.calculateScenario(base,{});
assert(Math.abs(b.revenue-60000)<0.01);
assert(Math.abs(b.personnel-12000)<0.01);
assert(Math.abs(b.otherCosts-30000)<0.01);
assert(Math.abs(b.gop-16800)<0.01);
assert(Math.abs(b.gopPct-28)<0.001);
const s=fs.calculateScenario(base,{occDelta:10,adrPct:10});
assert(Math.abs(s.occ-60)<0.001);
assert(Math.abs(s.rn-600)<0.001);
assert(Math.abs(s.adr-110)<0.001);
assert(s.revenue>b.revenue);
assert(s.gop>b.gop);
assert.strictEqual(fs.presets.conservative.occDelta,-3);
assert.strictEqual(fs.presets.upside.adrPct,3);
console.log('✓ forecast scenarios: projeção, custos, GOP e presets');
