const assert=require('assert');
const fs=require('fs');
const path=require('path');
const {ROOT,createSandbox,load}=require('./helpers/browser-sandbox');
const html=fs.readFileSync(path.join(ROOT,'index.html'),'utf8');
const sw=fs.readFileSync(path.join(ROOT,'service-worker.js'),'utf8');
const boot=fs.readFileSync(path.join(ROOT,'assets/js/core/04-bootstrap.js'),'utf8');
const nav=fs.readFileSync(path.join(ROOT,'assets/js/core/02-navigation-kpis.js'),'utf8');
const health=fs.readFileSync(path.join(ROOT,'assets/js/ui/cdn-healthcheck.js'),'utf8');
assert(html.includes('assets/js/core/05-performance.js'),'runtime de performance v18 deve estar ligado');
assert(!html.includes('<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js"'),'XLSX não deve bloquear o arranque');
assert(html.includes('rel="preconnect" href="https://cdnjs.cloudflare.com"'),'deve existir preconnect para Chart.js');
const ext=[...html.matchAll(/<script\b[^>]*\bsrc=["'][^"']+["'][^>]*>/gi)].map(m=>m[0]);
const normalExt=ext.filter(t=>!t.includes('06-version-guard-v29_1.js'));
assert(normalExt.length>20&&normalExt.every(t=>/\bdefer\b/i.test(t)),'scripts externos normais devem usar defer');
assert(ext.some(t=>t.includes('06-version-guard-v29_1.js')&&!/\bdefer\b/i.test(t)),'guard de versão deve ser bloqueante para correr antes do shell antigo');
assert(!/\n\s*rtRender\(\);\s*\n\s*calInit\(\);\s*\n\s*hoteisInit\(\);/.test(boot),'bootstrap não deve renderizar três módulos secundários no arranque');
assert(nav.includes("currentView === 'hoteis'")&&nav.includes("currentView === 'ocupacao'")&&nav.includes("currentView === 'instagram'"),'vistas pesadas devem renderizar sob pedido');
assert(nav.includes('__vgNumberFormats'),'formatadores numéricos devem ser reutilizados');
assert(nav.includes('resizeVisibleCharts'),'mudança de vista deve redimensionar apenas gráficos visíveis');
assert(health.includes('XLSX é carregado sob pedido'),'healthcheck deve reconhecer XLSX lazy');
assert(sw.includes("vg-operations-shell-v32")&&sw.includes('Promise.allSettled'),'service worker deve manter precache concorrente com cache versionada v22');
const s=createSandbox({requestIdleCallback:fn=>fn({didTimeout:false,timeRemaining:()=>10}),cancelIdleCallback(){}});s.window.performance={now:()=>10};s.performance=s.window.performance;load('assets/js/core/05-performance.js',s);assert.strictEqual(s.window.VG.performance.version,18);assert.strictEqual(typeof s.window.VG.performance.ensureXLSX,'function');assert.strictEqual(typeof s.window.VG.performance.report,'function');
console.log('✓ performance v18: defer, XLSX lazy, init por vista, formatters, charts e SW concorrente');
