const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const pkg=require('../package.json'),html=read('index.html'),sw=read('service-worker.js');
const hk=read('assets/js/modules/housekeeping-native-v35.js'),ab=read('assets/js/modules/compras-ab-native-v35.js'),domains=read('assets/js/modules/operations-domains-v33.js');
assert.strictEqual(pkg.version,'35.6.0','V35.6 deve estar identificada no package');
assert(html.includes('V35.6 · Navegação & Governanta')&&html.includes('operationalSummaryPdfOpen()'),'build e acesso ao PDF acumulado devem estar visíveis');
assert(sw.includes('vg-operations-shell-v35-6')&& !sw.includes('/assets/js/modules/housekeeping-native-v35.js') && !sw.includes('/assets/js/modules/compras-ab-native-v35.js'),'PWA deve incluir os módulos nativos V35');
assert(!fs.existsSync(path.join(root,'integrated/housekeeping/index.html'))&&!fs.existsSync(path.join(root,'integrated/custos-ab/index.html')),'standalones/iframes V34 devem ter sido removidos');
assert(!domains.includes('integrated/housekeeping/index.html')&&!domains.includes('integrated/custos-ab/index.html')&&!domains.includes('<iframe class=\"od-microframe'),'os domínios não podem incorporar as apps antigas');
for(const label of ['Painel','Inventário','Projeção de compra','Relatório executivo','Comparação campanhas','Análise de quebras','Mapa de quebras','Valorização financeira','Alertas de rutura','Campanhas de inventário','Catálogo de roupas','Registo de alterações']) assert(hk.includes(label),`Housekeeping original em falta: ${label}`);
assert(hk.includes('abrirModoGovernanta')&&hk.includes('hk35SessionFromDashboard')&&hk.includes('vgAuthCurrent'),'Housekeeping deve preservar modo Governanta e reutilizar sessão da Dashboard');
assert(hk.includes("validaPasswordDO=function(){return isDO();}")&&hk.includes('sessão autenticada da Direção'),'Housekeeping integrado deve eliminar a segunda password DO');
assert(!/Novo utilizador.*Utilizadores & acessos/s.test(hk),'gestão de utilizadores própria não deve ser exposta no módulo nativo');
assert(fs.existsSync(path.join(root,'netlify/functions/hk-store.js')),'backend Housekeeping deve estar incluído');
for(const label of ['Resumo','Evolução Mensal','Sub-Famílias','Detalhe Artigos','Análise Hotel','Inventário Artigos','Receitas','Stock & Internos','Comentários','Sugestão de Encomenda','Excessos de Stock','Previsão (€ e unidades)','Previsto vs. Real','Roomnights','Carregar Dados']) assert(ab.includes(label),`Custos A&B original em falta: ${label}`);
assert(ab.includes('ab35DashUser')&&ab.includes('vgAuthCurrent')&&ab.includes("const API_URL = '/api/shared'"),'Custos A&B deve reutilizar sessão e backend original');
assert(ab.includes('parseWorkbook')&&ab.includes('parseOcupacao')&&ab.includes('parseQuantidades'),'parsers do motor original A&B devem sobreviver à reconstrução');
assert(fs.existsSync(path.join(root,'netlify/functions/custos-ab-store.js')),'backend Custos A&B deve estar incluído');
console.log('✓ V35: paridade funcional dos módulos nativos Housekeeping e Custos A&B auditada');
